parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: laninadelmezcal
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: ~
    mailer_user: null
    mailer_password: null
    locale: en
    secret: faed65b6670198c4a275489e150e8b2445c9ea63
    database_path: null
