<?php

namespace Knp\Bundle\LastTweetsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TwitterController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Knp\Bundle\LastTweetsBundle\Controller\TwitterController();
        return $instance;
    }
}
