<?php

namespace Richpolis\FrontendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MensajesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Richpolis\FrontendBundle\Controller\MensajesController();
        return $instance;
    }
}
