<?php

namespace Richpolis\BackendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConfiguracionesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Richpolis\BackendBundle\Controller\ConfiguracionesController();
        return $instance;
    }
}
