<?php

namespace Richpolis\PublicacionesBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CategoriasPublicacionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Richpolis\PublicacionesBundle\Controller\CategoriasPublicacionController();
        return $instance;
    }
}
