<?php

namespace Richpolis\CategoriasGaleriaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CategoriasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Richpolis\CategoriasGaleriaBundle\Controller\CategoriasController();
        return $instance;
    }
}
