<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BotellasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotellasRepository extends EntityRepository
{
    public function getQueryBotellasActivas($todas=false){
		$query=$this->createQueryBuilder('p')
                    ->orderBy('p.botella', 'ASC');
        if(!$todas){
            $query->andWhere('p.isActive=:active')
                  ->setParameter('active', true);
        }

        return $query->getQuery();
    }
    
    public function getBotellasActivas($todas=false){
        $query=$this->getQueryBotellasActivas($todas);
        return $query->getResult();
    }
}
